version: '3'
services:
 db:
  image: andregaytan/servletmvcbd
  container_name: crudmvcbd
  ports:
   - "3306:3306"
 web:
   image: andregaytan/servletsmvcwebapp
   container_name: mvcservlets
   ports:
    - "8080:8080"
   links:
    - "db:webapp"

