version: '3'
services:
 db:
  image: mysql-servletsmvc-server
  container_name: crudmvcbd
  ports:
   - "3306:3306"
 web:
   image: tomcat-servletsmvc-server
   container_name: mvcservlets
   ports:
    - "8080:8080"
   links:
    - "db:webapp"
   build: mvcservlet

